server:
    port: 8080
    netty:
        max-chunk-size:
            64KB
spring:
  security:
    oauth2:
      client:
        provider:
          primary:
            issuer-uri: https://auth.oauth2
            token-uri: https://auth.oauth2/oauth2/token
            authorization-uri: https://auth.oauth2/oauth2/authorization
            jwk-set-uri: https://auth.oauth2/oauth2/keys
          microsoft:
            #common
            issuer-uri: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
          google:
            issuer-uri: https://accounts.google.com/.well-known/openid-configuration
          primary:
            client-id: primary
            client-secret: secret
            #client-authentication-method: client_secret_basic
            #client-authentication-method: client_secret_post
            #client-authentication-method: client_secret_jwt
            #client-authentication-method: private_key_jwt
            #client-authentication-method: none
            client-authentication-method: client_secret_basic
            #authorization-grant-type: authorization_code
            #authorization-grant-type: refresh_token
            #authorization-grant-type: client_credentials
            authorization-grant-type: client_credentials

r2dbc:
    enabled: true
    demo:
        url:r2dbc:h2:mem:///demo
        username:conn
        password:conn

